PYRAMID_LVLS: 4 #lvl idx start from 0 , e.g PYRAMID_LVLS = 3--> idx range [0,1,2]
THRESHOLD_BLOCK_DIM: 27
PIXEL_SELECTION_POT_DIM: 8
PIXEL_SELECTION_HERURISTIC_CONST: 7
PIXEL_SELECTION_NUM: 2200
PIXEL_SELECTION_DOWNWEIGHT: 0.7
PIXEL_SELECTION_RECURSIVE_LIMIT: 1

OPTIMIZATION_TRANS_SCALE:  1 
OPTIMIZATION_ROTATION_SCALE: 0.5
OPTIMIZATION_IDEPTH_SCALE: 1
OPTIMIZATION_ALPHA_SCALE: 10.0
OPTIMIZATION_BETA_SCALE: 1000.0

OPTIMIZATION_STEP_MIN : 1e-5
## lamda init and lamda min is specified in the config.h
OPTIMIZATION_LAMDA_MAX : 1e10
OPTIMIZATION_LAMDA_FAILED_PENALIZE: 4
OPTIMIZATION_LAMDA_SUCCESS_PENALIZE: 0.5

